version: "3.9"

services:
  apigateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    container_name: apigateway
    ports:
      - "8080:8080"
    env_file:
      - ./apigateway/.env
    depends_on:
      - demographics
      - notes
      - frontend-service
      - assessment
    networks:
      - app-network

  demographics:
    build:
      context: ./demographics
      dockerfile: Dockerfile
    container_name: demographics
    ports:
      - "8081:8081"
    env_file:
      - ./demographics/.env
    networks:
      - app-network

  notes:
    build:
      context: ./notes
      dockerfile: Dockerfile
    container_name: notes
    ports:
      - "8082:8082"
    env_file:
      - ./notes/.env
    networks:
      - app-network

  frontend-service:
    build:
      context: ./FlaskUI
      dockerfile: Dockerfile
    container_name: frontend-service
    ports:
      - "5000:5000"
    networks:
      - app-network

  assessment:
    build:
      context: ./assessment
      dockerfile: Dockerfile
    container_name: assessment
    ports:
      - "8083:8083"
    env_file:
      - ./assessment/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

