spring.application.name=notes

server.port=8082

#MongoDB Atlas Credentals
spring.data.mongodb.uri=${DB_CONNECT_STRING}
spring.mongodb.uri=${DB_CONNECT_STRING}


#this needs to be exactly the same as apigateway's jwt.secret as its the shared signing key
jwt.secret=${JWT_SECRET}

