server.port=8080
spring.application.name=apigateway

# Gateway Routes
spring.cloud.gateway.mvc.routes[0].id=demographics-patients
spring.cloud.gateway.mvc.routes[0].uri=lb://demographics
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/patients/**

spring.cloud.gateway.mvc.routes[1].id=frontend-ui
spring.cloud.gateway.mvc.routes[1].uri=lb://frontend-service
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/, /login, /static/**

# Load Balancer
spring.cloud.loadbalancer.clients.demographics.instances[0].uri=http://localhost:8081
spring.cloud.loadbalancer.clients.frontend-service.instances[0].uri=http://localhost:5000

# Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# JWT
jwt.secret=thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
jwt.expiration=3600000

