spring.application.name=demographics

server.port=${SERVER_PORT:8081}

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:my_database}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false
spring.jpa.show-sql=${JPA_SHOW_SQL:true}

# SQL Init
spring.sql.init.mode=always

# Shared Token
jwt.secret=${JWT_SECRET}






