spring.application.name=demographics

server.port=8081

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/my_database
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

# SQL Init
spring.sql.init.mode=always

# Remove or comment out H2 settings below
#spring.datasource.url=jdbc:h2:mem:demographicsdb;DB_CLOSE_DELAY=-1
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console



# Enable H2 Web Console for testing
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console




